### ISSUE TITLE
Old git history didn't come

### ISSUE THREAD

**Issue by davips** [end-to-end-data-science/pjautoml#1]
Old git history and github metainfo like stars, watch and forks from the old repository (paje-automl) are missing here.
Perhaps it is worth to just move the old one to this org.

Or, if it is really needed to recreate from scratch using a local git repository for some reason, I think it is also possible, but loosing metainfo. Depending on the reason, feel free to choose a point in time in history to include only commits up to that point (and discard the following ones), if needed.

**Comment by ealcobaca** [comment]
Thank you, Davi.
